//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspiraApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AspStudent
    {
        [Required]
        public int Id { get; set; }

        [Required]
        public string Aspira_Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        [EmailAddress]
        public string Email_Id { get; set; }

        [Required]
        public string Tech_stack { get; set; }

        [Required]
        public string Education { get; set; }

        [Required]
        public string Mobile_Number { get; set; }
    }
}
